import Head from 'next/head'
import Link from 'next/link'
import Image from "next/image"
import { useSession, signIn, signOut } from "next-auth/react"
<<<<<<< HEAD
import { useEffect, useState } from 'react'
=======
>>>>>>> b41781c3c4c747a4640a292b96320c2b6131622e
import ProfileDropdown from './profile/profileHeader'
import Button from './Button'

const Nav = () => {
  const { data: session } = useSession()
  const handleManageAccount = () => {
    console.log("Managing account")
  }
<<<<<<< HEAD
  const handleAddAccount = () => {
    console.log("Adding account")
  }
  const [isAdmin,setisAdmin] = useState(false)
  useEffect(()=>{
    if(session?.user.isAdmin){
      setisAdmin(true)
    }else{
      setisAdmin(false)
    }
  },[session])
  console.log("Admin session:",session)
=======



  const handleAddAccount = () => {
    console.log("Adding account")
  }
>>>>>>> b41781c3c4c747a4640a292b96320c2b6131622e

  return (
    <>
      <Head>
        <title>Video course starter kit – powered by Mux</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className='p-4 mb-6 flex items-center space-x-3'>
<<<<<<< HEAD
      <ul className='flex gap-2'>
  <li>
    <Link href="/" className='underline'>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
        <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
      </svg>
    </Link>
  </li>
  {session && isAdmin && (
    <>
      <li>
        <Link href="/admin" className='underline'>
          Admin
        </Link>
      </li>
      <li>
        <Link href="/admin/users" className='underline'>
          Users
        </Link>
      </li>
    </>
  )}
</ul>

=======
        <ul className='flex gap-2'>
          <li>
            <Link href="/" className='underline'>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
              </svg>
            </Link>
          </li>
          {session && session.user?.isAdmin && (
            <li>
              <Link href="/admin" className='underline'>
                Admin
              </Link>
            </li>
          )}
        </ul>
>>>>>>> b41781c3c4c747a4640a292b96320c2b6131622e
        <div className='flex-1 flex justify-center'>
          <Link href="/" className="flex justify-center items-center">
              <Image
              alt="Video course starter kit"
              height={32}
              src="/images/mux-logo.png"
              width={100}
            />
            {/* <span className="inline-block ml-3 font-medium truncate text-slate-700">
              Video Course Starter Kit
            </span> */}
          </Link>
        </div>
        <div className='text-right text-sm'>
<<<<<<< HEAD
          {session ? (     <ProfileDropdown
=======
          {session ? (
            // <div className='text-slate-700'>
            //   Signed in as {session.user?.email} <br />
            //   <button className='underline' onClick={() => signOut()}>Sign out</button>
            // </div>
             <ProfileDropdown
>>>>>>> b41781c3c4c747a4640a292b96320c2b6131622e
             name={session.user.name || ""}
             email={session.user.email || ""}
             avatarUrl="/placeholder.svg?height=32&width=32"
             onManageAccount={handleManageAccount}
             onSignOut={signOut}
             onAddAccount={handleAddAccount}
           />
          ) : (
            <p>
              <Button onClick={() => signIn()}>Sign in</Button>
            </p>
          )}
        </div>
      </nav>
    </>
  )
}

export default Nav;